# ~/.bashrc

# GPG/SSH Agent Setup (for yubikey using gpg-agent)
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null

# Yubikey-agent setup (for yubikey using yubikey-agent)
# export SSH_AUTH_SOCK="$(brew --prefix)/var/run/yubikey-agent.sock"
